#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#echo "$(tput setaf 4)正在初始化子模块... $(tput setaf 3)"
#git submodule update --init
#
##echo "$(tput setaf 4)正在拉取子模块... $(tput setaf 3)"
##git submodule foreach "git pull"
#
#echo "正在更新 src/common 子模块..."
#git submodule --init
#git submodule update --remote --merge -- src/common
#
## 如果子模块有更新，提交这些更改
#if git diff --quiet -- src/common; then
#  echo "src/common 子模块已经是最新的"
#else
#  echo "src/common 子模块有更新，正在提交更改..."
#  git add src/common
#  git commit -m "chore: 更新 src/common 子模块" --no-verify
#  echo "子模块更新已提交"
#fi